export const words = [
    { description: 'we do this every day', answer: 'sleep' },
    { description: 'you do this when you are hungry', answer: 'eat' },
    { description: 'this happens when the sun rises', answer: 'morning' },
    { description: 'you do this to stay healthy', answer: 'exercise' },
    { description: 'we do this to relax our minds', answer: 'meditate' },
    { description: 'we do this to learn', answer: 'study' },
    { description: 'you do this when you\'re dirty', answer: 'shower' },
    { description: 'you do this when you\'re cold', answer: 'shiver' },
    { description: 'this helps you move faster', answer: 'run' },
    { description: 'you do this to express happiness', answer: 'smile' },
    { description: 'you do this when you\'re sad', answer: 'cry' },
    { description: 'you do this to meet people', answer: 'socialize' },
    { description: 'you do this to celebrate', answer: 'party' },
    { description: 'you do this when you\'re tired', answer: 'rest' },
    { description: 'we do this to communicate', answer: 'talk' },
    { description: 'you do this when you\'re angry', answer: 'shout' },
    { description: 'we do this to clean our clothes', answer: 'wash' },
    { description: 'you do this before eating', answer: 'cook' },
    { description: 'you do this in your free time', answer: 'relax' },
    { description: 'you do this at school', answer: 'learn' },
    { description: 'you do this when you\'re excited', answer: 'jump' },
    { description: 'you do this to keep your teeth clean', answer: 'brush' },
    { description: 'we do this to travel far', answer: 'fly' },
    { description: 'you do this with a ball', answer: 'kick' },
    { description: 'we do this to hear music', answer: 'listen' },
    { description: 'you do this on a keyboard', answer: 'type' },
    { description: 'you do this to open a book', answer: 'read' },
    { description: 'you do this when you’re in a hurry', answer: 'rush' },
    { description: 'you do this to capture a photo', answer: 'snap' },
    { description: 'we do this to keep fit', answer: 'workout' },
    { description: 'we do this in a pool', answer: 'swim' },
    { description: 'we do this in winter', answer: 'ski' },
    { description: 'you do this on a bike', answer: 'ride' },
    { description: 'you do this to play music', answer: 'sing' },
    { description: 'you do this to be funny', answer: 'joke' },
    { description: 'you do this to calm down', answer: 'breathe' },
    { description: 'you do this when something is funny', answer: 'laugh' },
    { description: 'you do this to build things', answer: 'create' },
    { description: 'you do this with a pencil', answer: 'draw' },
    { description: 'you do this when something smells bad', answer: 'grimace' },
    { description: 'you do this before a race', answer: 'stretch' },
    { description: 'you do this to move quietly', answer: 'sneak' },
    { description: 'you do this when you\'re shocked', answer: 'gasp' },
    { description: 'you do this to learn a language', answer: 'practice' },
    { description: 'you do this when it\'s hot', answer: 'sweat' },
    { description: 'you do this with your phone', answer: 'scroll' },
    { description: 'you do this when something breaks', answer: 'fix' },
    { description: 'you do this to cross the road', answer: 'walk' },
    { description: 'you do this on stairs', answer: 'climb' },
    { description: 'you do this to show respect', answer: 'bow' },
    { description: 'you do this to tell a story', answer: 'narrate' },
    { description: 'you do this when you\'re sick', answer: 'cough' },
    { description: 'you do this when you\'re allergic', answer: 'sneeze' },
    { description: 'you do this with a pen', answer: 'write' },
    { description: 'you do this when you forget something', answer: 'think' },
    { description: 'you do this to show agreement', answer: 'nod' },
    { description: 'you do this to protect yourself', answer: 'hide' },
    { description: 'you do this when you make a mistake', answer: 'apologize' },
    { description: 'you do this before sleeping', answer: 'yawn' },
    { description: 'you do this when you\'re scared', answer: 'tremble' },
    { description: 'you do this with your eyes', answer: 'blink' },
    { description: 'you do this when you explore', answer: 'discover' },
    { description: 'you do this to help someone', answer: 'support' },
    { description: 'you do this to start your day', answer: 'wake' },
    { description: 'you do this with food', answer: 'chew' },
    { description: 'you do this to get clean', answer: 'bathe' },
    { description: 'you do this to learn from mistakes', answer: 'reflect' },
    { description: 'you do this to test knowledge', answer: 'quiz' },
    { description: 'you do this to get stronger', answer: 'train' },
    { description: 'you do this to fix code', answer: 'debug' },
    { description: 'you do this to find something', answer: 'search' },
    { description: 'you do this with your friends', answer: 'chat' },
    { description: 'you do this when you’re unsure', answer: 'hesitate' },
    { description: 'you do this when you compete', answer: 'challenge' },
    { description: 'you do this with a problem', answer: 'solve' },
    { description: 'you do this when you explore nature', answer: 'hike' },
    { description: 'you do this to keep a memory', answer: 'record' },
    { description: 'you do this with a map', answer: 'navigate' },
    { description: 'you do this in a museum', answer: 'observe' },
    { description: 'you do this to prepare food', answer: 'slice' },
    { description: 'you do this when you want fun', answer: 'play' },
    { description: 'you do this to stay calm', answer: 'focus' },
    { description: 'you do this when you need help', answer: 'ask' },
    { description: 'you do this to prove something', answer: 'demonstrate' },
    { description: 'you do this when you travel', answer: 'pack' },
    { description: 'you do this when something is beautiful', answer: 'admire' },
    { description: 'you do this when you agree', answer: 'accept' },
    { description: 'you do this to win', answer: 'compete' },
    { description: 'you do this to reach a goal', answer: 'achieve' },
    { description: 'you do this when you get news', answer: 'react' },
    { description: 'you do this to relax your body', answer: 'lay' },
    { description: 'you do this with a balloon', answer: 'inflate' },
    { description: 'you do this with a camera', answer: 'record' },
    { description: 'you do this to grow stronger', answer: 'improve' },
    { description: 'you do this when you’re grateful', answer: 'thank' },
    { description: 'you do this when you help someone', answer: 'assist' },
    { description: 'you do this with fire', answer: 'burn' },
    { description: 'you do this to help a plant', answer: 'water' },
    { description: 'you do this to test yourself', answer: 'practice' },
    { description: 'you do this with your pet', answer: 'feed' },
    { description: 'you do this when you’re unsure', answer: 'guess' },
    { description: 'you do this when you try again', answer: 'retry' },
    { description: 'you do this to stay focused', answer: 'concentrate' },
  ];
  